[tools]
rojo = { github = "rojo-rbx/rojo", version = "7.0.0" }
selene = { github = "Kampfkarren/selene", version = "0.20.0" }
stylua = { github = "JohnnyMorganz/StyLua", version = "0.14.2" }
rbxcloud = { github = "Sleitnick/rbxcloud", version = "0.1.0-alpha.10" }
